# Site settings
title: "Time Based Photography"
email: kegan@risd.edu
description: > # this means to ignore newlines until "baseurl:"
  Kelly Egan, Instructor &bull; PHOTO-5312, Spring 2019, Thursday, 1:10&ndash;6:10p.m.
baseurl: "/TimeBasedPhotography" # the subpath of your site, e.g. /blog
plugins: [jekyll-paginate]
